local Pets = {}

Pets.allPets = {

	["1"] = {name = "Brri Brri Bicus Dicus Bombicus"},
	["2"] = {name = "Tralalero Tralala"},
	["3"] = {name = "Madundung"},
	["4"] = {name = "Bombardino Crocodillo"},
	["5"] = {name = "Brr Brr Patapim"},
	["6"] = {name = "Chimpanzini Bananini"},
	["7"] = {name = "Udindindindin"},
	["8"] = {name = "Trippi Troppi"},
	["9"] = {name = "Tung Tung Tung Sahur"},
	["10"] = {name = "Capuchino Assassino"},
	["11"] = {name = "Aram Ram Ramar"},
	["12"] = {name = "Lirili Larila"},
	["13"] = {name = "Bombardino Gusini"},
	["14"] = {name = "Garam"},
	["15"] = {name = "Boneca Ambalabu"},
	["16"] = {name = "Orcalero Orcala"},
	["17"] = {name = "Los Orcaleritos"},
	["18"] = {name = "Los Tralaleritos"},
	["19"] = {name = "Los Tralaleritas"},
	["20"] = {name = "Los Tung Tungcitos"},
	["21"] = {name = "Nucleauro Dinosauro"},
	["22"] = {name = "Bombobona Pecorona"},
	["23"] = {name = "Lokomomu Milkuma"},
	["24"] = {name = "Trenostruzzo Turbo"},
	["25"] = {name = "Bombombini Gussini"},
	["26"] = {name = "Snakuli Bananuli"},
	["27"] = {name = "Noobini Pizzanini"},
	["28"] = {name = "Tigrulini Watermelini"},
	["29"] = {name = "Pípi Potato"},
	["30"] = {name = "Pípi Kiwi"},
	["31"] = {name = "Agarrini la Palini"},
	["32"] = {name = "Avocadini Guffo"},
	["33"] = {name = "Avocadorilla"},
	["34"] = {name = "Ballerina Cappuccina"},
	["35"] = {name = "Ballerino Lololo"},
	["36"] = {name = "Bambini Crostini"},
	["37"] = {name = "Bananita Dolphinita"},
	["38"] = {name = "Bandito Bobritto"},
	["39"] = {name = "Blueberrinni Octopusini"},
	["40"] = {name = "Burbaloni Loiloli"},
	["41"] = {name = "Cacto Hipopotamo"},
	["42"] = {name = "Cavallo Virtuoso"},
	["43"] = {name = "Chef Crabracadabra"},
	["44"] = {name = "Chimpanzini Spiderini"},
	["45"] = {name = "Cocofanto Elefanto"},
	["46"] = {name = "Dragon Cannelloni"},
	["47"] = {name = "Espresso Signora"},
	["48"] = {name = "Furliflura"},
	["49"] = {name = "Frigo Camelo"},
	["50"] = {name = "Gangster Footera"},
	["51"] = {name = "Gattaino Neonino"},
	["52"] = {name = "Gattaino Nyanino"},
	["53"] = {name = "Girafa Celestre"},
	["54"] = {name = "Glorbo Fruttodrillo"},
	["55"] = {name = "Gorillo Watermelondrillo"},
	["56"] = {name = "Graipuss Medussi"},
	["57"] = {name = "La Grande Combinasion"},
	["58"] = {name = "La Vaca Saturno Saturnita"},
	["59"] = {name = "Lionel_Cactuseli"},
	["60"] = {name = "Orangutini Ananassini"},
	["61"] = {name = "Pandaccini Bananini"},
	["62"] = {name = "Penguino Cocosino"},
	["63"] = {name = "Perochello Lemonchello"},
	["64"] = {name = "Pi Pi Watermelon"},
	["65"] = {name = "Piccione Macchina"},
	["66"] = {name = "Pot Hotspot"},
	["67"] = {name = "Rhino Toasterino"},
	["68"] = {name = "Salamino Penguino"},
	["69"] = {name = "Sigma Boy"},
	["70"] = {name = "Spiderini Dragonfrutini"},
	["71"] = {name = "Spioniro Golubiro"},
	["72"] = {name = "Statutino Libertino"},
	["73"] = {name = "Strawberrelli Flamingelli"},
	["74"] = {name = "Svinina Bombardino"},
	["75"] = {name = "Ta Ta Ta Ta Sahur"},
	["76"] = {name = "Talpa Di Fero"},
	["77"] = {name = "Ti Ti Ti Sahur"},
	["78"] = {name = "Tigroli Gre Frutonni"},
	["79"] = {name = "Tortutgini Dragonfrutini"},
	["80"] = {name = "Trulimero Trulicina"},
	["81"] = {name = "Tukanno Bananno"},
	["82"] = {name = "Zibra Zubra Zibralini"},

}

return Pets
